### ISSUE TITLE
Recover a bricked VeraSecure

### ISSUE THREAD

**Issue by nodecentral** [vwout/vera-toolchain#2]
Hi, long shot I guess, but can I use any of this to help restore a bricked VeraSecure ?

**Comment by vwout** [comment]
I don't have any experience unbricking a Vera. When you don't have access to a device, this toolchain probably won't be of any help, since its only use is building binaries to run on Vera. Unfortunately, I do not know yet how to build a full firmware for Vera.
How badly bricked is it?

**Comment by nodecentral** [comment]
> How badly bricked is it?

Not sure..

The ‘power’ led is constant and the ‘internet’  led flashes, and looking at the back the green LED on the network /rj45 port it’s continually pulses (I assume attempting something) , but I can never see it obtain an ip and appear on the network. (Vera support have wiped their hands of it as it’s out of warrenty)

I’ve tried Wireshark (which is new to me) to see if there are any arp type requests but I can’t see anything , so it’s not clear what the network activity is (assuming it’s something ?) 

any suggestions/ideas would be appreciated

**Comment by vwout** [comment]
I assume this is the same case as documented in https://smarthome.community/topic/134/recover-an-assumed-bricked-vera-secure?

Do you see any network activity during this reset method?
>  You will need to set the device in bootloader mode by powering it up while maintaining the the reset button pressed

Since the device is out of warrany, and broken, you might want to open it up. May well be the device has a service UART or JTAG header that could be used for recovery.

**Comment by nodecentral** [comment]
Old post, but just wanted to update it to say - i did open it up in the end and connected via the USB/Serial connection on the board and i tried numerous things and eventually it loaded up again and worked, sadly I can’t recall the exact thing that did it, as it was more desperation at the end :-)
